[package]
name = "aopt"
version = "0.7.1"
authors = ["araraloren <blackcatoverwall@gmail.com>"]
edition = "2021"
license = "MPL-2.0"
description = "A flexible and typed getopt tools"
repository = "https://github.com/araraloren/aopt/"
keywords = ["getopt", "cli"]
categories = ["command-line-interface"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1.0.0"
regex = "1.5.0"
ahash = "0.8.0"
serde = { version = "1.0", features = [ "derive" ] }
tracing = "0.1.37"

[features]
sync = []
utf8 = []