[workspace]

members = [
    "aopt",
    "aopt-help",
    "cote",
    "cote-derive",
    # "index-constituent",
    # "simple-find-file",
    # "snowball-follow",
]

[patch.crates-io]
cote = {path = "cote"}
aopt = { path = "aopt" }
cote-derive = { path = "cote-derive" }