[package]
name = "cote"
version = "0.2.0"
authors = ["araraloren <araraloren@gmail.com>"]
edition = "2021"
license = "MPL-2.0"
description = "Quickly build your command line utils"
repository = "https://github.com/araraloren/aopt/"
keywords = ["getopt", "cli"]
categories = ["command-line-interface"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aopt = { version = "0.8" }
aopt-help = { version = "0.3" }
serde = { version = "1.0", features = [ "derive" ] }

[features]
sync = ["aopt/sync"]
utf8 = ["aopt/utf8"]