[package]
name = "cote"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aopt = { version = "0.7.0" }
aopt-help = { version = "0.3.1" }