[package]
name = "cote"
version = "0.3.0"
authors = ["araraloren <araraloren@gmail.com>"]
edition = "2021"
license = "MPL-2.0"
description = "Quickly build your command line utils"
repository = "https://github.com/araraloren/aopt/"
keywords = ["getopt", "cli"]
categories = ["command-line-interface"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aopt = { git = "https://github.com/araraloren/aopt", branch = "cote_research", features = ["serde"] }
cote-derive = { git = "https://github.com/araraloren/aopt", branch = "cote_research" }
# aopt = { path = "../aopt", features = ["serde"] }
# cote-derive = { path = "../cote-derive" }
aopt-help = { version = "0.3" }
serde = { version = "1.0", features = [ "derive" ] }
tracing-subscriber = { version = "0.3.2", features = ["env-filter"] }

[[bin]]
name="main"
path="src/main.rs"

[features]
sync = ["aopt/sync"]
utf8 = ["aopt/utf8"]
log = ["aopt/log"]