[package]
name = "snowball"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopt-rs = { path = "../getopt-rs" }
getopt-rs-help = { path = "../getopt-rs-help" }
tracing-subscriber = "0.2"
color-eyre = "0.5"
reqwest = { version = "0.11", features = ["json", "gzip", "cookies"] }
tokio = { version = "1", features = ["full"] }
json = "0.12"