[package]
name = "snowball-follow"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopt-rs = { path = "../getopt-rs" }
tracing-subscriber = "0.2"
color-eyre = "0.5"